micronaut:
  application:
    name: hello-world
  router:
    static-resources:
      swagger:
        enabled: true
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  openapi:
    additional:
      files: ${project.home}/src/test/resources/swagger
  server:
    cors:
      enabled: true

#数据源配置的开始
datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
#数据源配置的结束
#flyway的配置开始
flyway:
  datasources:
    default:
      locations: classpath:databasemigrations
#flyway的配置结束

